[development]
address = "localhost"
port = 8001
elastic_url = "http://clayface.caida.org:9200"
simple_page = true

[production]
address = "0.0.0.0"
port = 80
elastic_url = "http://clayface.caida.org:9200"
simple_page = true
